name: apex
description: "Apex: Unofficial Formula 1 app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.6
  http: ^1.6.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: GeistMono
      fonts:
        - asset: fonts/GeistMono-Thin.ttf
        - asset: fonts/GeistMono-ExtraLight.ttf
        - asset: fonts/GeistMono-Light.ttf
        - asset: fonts/GeistMono-Regular.ttf
        - asset: fonts/GeistMono-Medium.ttf
        - asset: fonts/GeistMono-SemiBold.ttf
        - asset: fonts/GeistMono-Bold.ttf
        - asset: fonts/GeistMono-ExtraBold.ttf
        - asset: fonts/GeistMono-Black.ttf